### ISSUE TITLE
Slowness with big number of ports

### ISSUE THREAD

**Issue by mc2zp** [clasiru/TCP_Scanner#1]
Currently, checker works in one thread mode, but you may run it in asynch mode (Py3.7+) and check ports in async mode, it will be much faster.
What do you think?
https://docs.python.org/3/library/asyncio.html

**Comment by clasiru** [comment]
Thank you for your suggestion. Yes, that will slow, but the problem is if we go too fast target system will flag our connection too soon. If the Asynchronous I/O library will not affect that, I will try it.
